#docker
FROM ubuntu:14.04

MAINTAINER 0303 <farmatholin@gmail.com>

RUN apt-get update && \
    apt-get install -y python-software-properties software-properties-common
RUN add-apt-repository -y ppa:gluster/glusterfs-3.5 && \
    apt-get update && \
    apt-get install -y glusterfs-client supervisor

RUN mkdir -p /var/log/supervisor

ENV DEBUG 1


RUN mkdir -p /usr/local/bin
ADD ./scripts /usr/local/bin
RUN chmod +x /usr/local/bin/*.sh
ADD ./scripts/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
EXPOSE 22

CMD ["/usr/local/bin/docker_run.sh"]