glusterfs:
      vol: ims
      brick: "/gluster_volume"
      vagrant_file: "/etc/pgluster/Vagrantfile"
      server:
          name: glusterfs-server
          image: "farmatholin/glusterfs-server:latest"
          key: "/etc/pgluster/key/open_key"

      client:
          name: glusterfs-client
          image: "farmatholin/glusterfs-client:latest"
          workers: 5
      web:
          name: nginx-glusterfs
          image: "farmatholin/glusterfs-client-nginx:latest"
          port: "9092"
mongo:
      name: pgluster
      host: localhost
      port: 27017
      server_collection: "servers"
      status_collection: "status"