glusterfs:
      vol: ims
      brick: "/gluster_volume"
      server:
          name: glusterfs-server
          image: "farmatholin/glusterfs-server:latest"
          key: "/etc/pgluster/key/open_key"
          credentials:
            - user: user
              ip: "192.168.94.134"
            - user: user
              ip: "192.168.94.136"
      client:
          name: glusterfs-client
          image: "farmatholin/glusterfs-client:latest"
          workers: 5
      web:
          name: nginx-glusterfs
          image: "farmatholin/glusterfs-client-nginx:latest"
          port: "9092"