#docker
FROM buildpack-deps:jessie

MAINTAINER Vladislav Marin <farmatholin@gmail.com>

RUN wget -O - http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/pub.key | apt-key add -

RUN echo deb http://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.6/Debian/jessie/apt jessie main > /etc/apt/sources.list.d/gluster.list && \
    apt-get update && \
    apt-get install -y glusterfs-server supervisor

RUN mkdir -p /var/log/supervisor

ENV DEBUG 1

RUN mkdir -p /usr/local/bin
ADD ./scripts /usr/local/bin
RUN chmod +x /usr/local/bin/*.sh
ADD ./scripts/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]